services:
  # Backend service
  - type: web
    name: backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn backend.wsgi:application --log-file -
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

  # Frontend service
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_VERSION
        value: 16.0.0
      - key: VITE_API_URL
        value: "https://backend.onrender.com" 